# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d51217e2bac0361863036f9f01aab47bb9e2fa8ba4fc251488448107faa86bcf8deff03d3c3994bf84b3d4ce6a777cc56db8b0eecfaa3eee15da46deed057aac

test:
  secret_key_base: ba0a4c5d234ca9a528c9474c839547adfb42b7fc94de0b8bdaf15d0a0ef2f405847411208a53ac474b93e854faaf49138fb45bb22bf6bdfc86556877568ed0bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
